
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,apiError} from '../services/api';
import {useEffect,useState} from 'react';
import {Icon} from '../components/Icons';

export default function Admin(){
 const qc=useQueryClient();
 const [name,setName]=useState(''),[code,setCode]=useState(''),[description,setDescription]=useState(''),[capacity,setCapacity]=useState('100'),[avgTime,setAvgTime]=useState('10');
 const [staffName,setStaffName]=useState(''),[staffEmail,setStaffEmail]=useState(''),[staffPassword,setStaffPassword]=useState(''),[serviceIds,setServiceIds]=useState<string[]>([]);
 const [orgName,setOrgName]=useState(''),[orgAddress,setOrgAddress]=useState(''),[orgDescription,setOrgDescription]=useState('');
 const [error,setError]=useState('');
 const [success,setSuccess]=useState('');
 const me=useQuery({queryKey:['me'],queryFn:async()=>{const r=await api.get('/auth/me');return r.data}});
 const orgs=useQuery({queryKey:['my-org'],queryFn:async()=>{const r=await api.get('/organizations/mine');return r.data}});
 const stats=useQuery({queryKey:['stats'],queryFn:async()=>{const r=await api.get('/analytics/overview');return r.data}});
 const org=orgs.data;
 useEffect(()=>{if(org){setOrgName(org.name||'');setOrgAddress(org.address||'');setOrgDescription(org.description||'')}},[org?.id]);
 useEffect(()=>{if(orgs.error){setError(apiError(orgs.error,'Could not load your organization.'))}},[orgs.error]);
 const services=useQuery({queryKey:['admin-services',org?.id],queryFn:async()=>{const r=await api.get(`/organizations/${org.id}/services`);return r.data},enabled:Boolean(org?.id)});
 const staff=useQuery({queryKey:['staff',org?.id],queryFn:async()=>{const r=await api.get(`/organizations/${org.id}/staff`);return r.data},enabled:Boolean(org?.id)});
 async function saveOrg(){if(!org)return;setError('');setSuccess('');try{await api.patch(`/organizations/${org.id}`,{name:orgName.trim(),address:orgAddress.trim(),description:orgDescription.trim(),timezone:org.timezone});await qc.invalidateQueries({queryKey:['my-org']});setSuccess('Organization profile saved.')}catch(e){setError(apiError(e,'Could not update organization.'))}}
 async function createService(){if(!org)return;setError('');setSuccess('');if(!name.trim()||!code.trim()){setError('Enter both a service name and code.');return}const cap=parseInt(capacity,10);const time=parseInt(avgTime,10);if(isNaN(cap)||cap<1){setError('Queue capacity must be at least 1.');return}if(isNaN(time)||time<1){setError('Average service time must be at least 1 minute.');return}try{await api.post(`/organizations/${org.id}/services`,{name:name.trim(),code:code.trim().toUpperCase(),average_service_time:time,queue_capacity:cap,description:description.trim()||null,operating_hours:{}});setName('');setCode('');setDescription('');setCapacity('25');setAvgTime('10');await qc.invalidateQueries({queryKey:['admin-services',org.id]});setSuccess('Service created successfully.')}catch(e){setError(apiError(e,'Could not create service.'))}}
 async function deactivateService(id:string){if(!confirm('Deactivate this service?'))return;try{await api.delete(`/services/${id}`);qc.invalidateQueries({queryKey:['admin-services',org.id]})}catch(e){setError(apiError(e,'Could not deactivate service.'))}}
 async function createStaff(){if(!org)return;setError('');setSuccess('');if(!staffName.trim()||!staffEmail.trim()||!staffPassword){setError('Enter the staff name, email and password.');return}if(staffPassword.length<8){setError('Staff password must contain at least 8 characters.');return}if(serviceIds.length===0){setError('Select at least one service for this staff member.');return}try{await api.post(`/organizations/${org.id}/staff`,{name:staffName.trim(),email:staffEmail.trim(),password:staffPassword,service_ids:serviceIds});setStaffName('');setStaffEmail('');setStaffPassword('');setServiceIds([]);await qc.invalidateQueries({queryKey:['staff',org.id]});setSuccess('Staff account created and service access assigned.')}catch(e){setError(apiError(e,'Could not create staff account.'))}}
 async function removeStaff(id:string){if(!org||!confirm('Remove this staff member from the organization?'))return;try{await api.delete(`/organizations/${org.id}/staff/${id}`);qc.invalidateQueries({queryKey:['staff',org.id]})}catch(e){setError(apiError(e,'Could not remove staff member.'))}}
 function toggleService(id:string){setServiceIds(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id])}
 return <div className="page-wrap py-10 sm:py-14">
  <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-violet-600">Organization admin</p><h1 className="mt-2 text-4xl font-black">{org?.name||'Organization dashboard'}</h1><p className="mt-2 text-slate-500">Manage your services, staff, profile and operational performance.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700"><Icon name="shield" size={15}/> Admin access</span></div>
  <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Customers',stats.data?.total_customers],['Waiting',stats.data?.queue_length],['Completed',stats.data?.completed_tokens],['Avg wait',`${stats.data?.average_wait||0}m`]].map(([k,v])=><div className="card p-5" key={String(k)}><p className="text-sm font-semibold text-slate-500">{k}</p><p className="mt-1 text-3xl font-black stat-number">{v??'—'}</p></div>)}</div>
  {error&&<div role="alert" className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
  {success&&<div role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{success}</div>}
  <div className="mt-8 card p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Organization profile</h2><p className="mt-1 text-sm text-slate-500">Control how your service provider appears to customers.</p></div><Icon name="settings" className="text-violet-600"/></div><div className="mt-5 grid gap-3 md:grid-cols-3"><input className="input" value={orgName} onChange={e=>setOrgName(e.target.value)} placeholder="Organization name"/><input className="input" value={orgAddress} onChange={e=>setOrgAddress(e.target.value)} placeholder="Address"/><input className="input" value={orgDescription} onChange={e=>setOrgDescription(e.target.value)} placeholder="Description"/></div><button className="btn btn-primary mt-4" onClick={saveOrg}>Save organization</button></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2">
   <div className="card p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Services</h2><p className="mt-1 text-sm text-slate-500">Create and configure what customers can join.</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon name="queue"/></span></div><div className="mt-5 space-y-3">{services.data?.map((s:any)=><div key={s.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{s.name}</p><p className="mt-1 text-xs text-slate-500">{s.code} · {s.average_service_time} min average · capacity {s.queue_capacity}</p></div><button className="btn btn-danger !px-3 !py-2 text-xs" onClick={()=>deactivateService(s.id)}>Deactivate</button></div></div>)}</div><div className="mt-6 border-t border-slate-100 pt-6"><h3 className="font-extrabold">Add service</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Service name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Code e.g. GEN" value={code} onChange={e=>setCode(e.target.value)}/><input className="input" type="number" min="1" max="10000" placeholder="Queue capacity" value={capacity} onChange={e=>setCapacity(e.target.value)}/><input className="input" type="number" min="1" max="240" placeholder="Avg time (mins)" value={avgTime} onChange={e=>setAvgTime(e.target.value)}/><input className="input sm:col-span-2" placeholder="Short description" value={description} onChange={e=>setDescription(e.target.value)}/></div><button className="btn btn-primary mt-3 w-full" onClick={createService}><Icon name="plus" size={16}/> Create service</button></div></div>
   <div className="card p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Staff</h2><p className="mt-1 text-sm text-slate-500">Create accounts and assign them to services.</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-600"><Icon name="users"/></span></div><div className="mt-5 space-y-3">{staff.data?.map((s:any)=><div key={s.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-sm font-black">{s.name.charAt(0).toUpperCase()}</span><div><p className="font-bold">{s.name}</p><p className="text-xs text-slate-500">{s.email}</p></div></div><button className="btn btn-danger !px-3 !py-2 text-xs" onClick={()=>removeStaff(s.id)}>Remove</button></div>)}</div><div className="mt-6 border-t border-slate-100 pt-6"><h3 className="font-extrabold">Add staff member</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Full name" value={staffName} onChange={e=>setStaffName(e.target.value)}/><input className="input" type="email" placeholder="Email" value={staffEmail} onChange={e=>setStaffEmail(e.target.value)}/><input className="input sm:col-span-2" type="password" placeholder="Temporary password (8+)" value={staffPassword} onChange={e=>setStaffPassword(e.target.value)}/></div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">Assign services</p><div className="mt-2 grid gap-2">{services.data?.map((s:any)=><label key={s.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" checked={serviceIds.includes(s.id)} onChange={()=>toggleService(s.id)}/><span className="font-semibold">{s.name}</span></label>)}</div><button className="btn btn-primary mt-4 w-full" onClick={createStaff}><Icon name="plus" size={16}/> Create staff account</button></div></div>
  </div>
 </div>
}
