import {useQuery} from '@tanstack/react-query';
import {api,apiError} from '../services/api';
import {useState} from 'react';
import {Icon} from '../components/Icons';

export default function Appointments(){
 const [orgId,setOrgId]=useState(''); const [serviceId,setServiceId]=useState(''); const [date,setDate]=useState(''); const [start,setStart]=useState('10:00'); const [end,setEnd]=useState('10:15'); const [message,setMessage]=useState('');
 const orgs=useQuery({queryKey:['orgs'],queryFn:async()=>{const r=await api.get('/organizations');return r.data}});
 const services=useQuery({queryKey:['services',orgId],queryFn:async()=>{const r=await api.get(`/organizations/${orgId}/services`);return r.data},enabled:Boolean(orgId)});
 const appts=useQuery({queryKey:['appointments'],queryFn:async()=>{const r=await api.get('/appointments');return r.data}});
 async function book(){setMessage('');try{await api.post('/appointments',{service_id:serviceId,appointment_date:date,start_time:start,end_time:end});setMessage('Appointment booked successfully. A notification was created and an email is being delivered.');appts.refetch()}catch(e){setMessage(apiError(e,'Unable to book appointment.'))}}
 const today=new Date(); const localToday=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
 return <div className="page-wrap py-10 sm:py-14"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-indigo-600">Customer portal</p><h1 className="mt-2 text-4xl font-black">Appointments</h1><p className="mt-2 text-slate-500">Choose a service and time slot. Successful bookings create an in-app notification and an email when SMTP is configured.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="card p-7"><h2 className="text-xl font-black">Book an appointment</h2><div className="mt-6 space-y-4"><div><label className="label">Organization</label><select className="input" value={orgId} onChange={e=>{setOrgId(e.target.value);setServiceId('')}}><option value="">Choose an organization</option>{orgs.data?.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><div><label className="label">Service</label><select className="input" value={serviceId} onChange={e=>setServiceId(e.target.value)} disabled={!orgId}><option value="">Choose a service</option>{services.data?.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="label">Date</label><input className="input" type="date" min={localToday} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Start</label><input className="input" type="time" value={start} onChange={e=>setStart(e.target.value)}/></div><div><label className="label">End</label><input className="input" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><button className="btn btn-primary w-full" disabled={!serviceId||!date||!start||!end||start>=end} onClick={book}><Icon name="calendar" size={16}/> Book appointment</button>{message&&<p className="rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-600">{message}</p>}</div></div><div className="card p-7"><h2 className="text-xl font-black">Your appointments</h2><div className="mt-5 space-y-3">{appts.data?.length?appts.data.map((a:any)=><div className="rounded-2xl border border-slate-200 p-4" key={a.id}><div className="flex justify-between gap-3"><div><p className="font-bold">{a.service_name||services.data?.find((s:any)=>s.id===a.service_id)?.name||'Service'}</p><p className="mt-1 text-sm text-slate-500">{a.appointment_date} · {String(a.start_time).slice(0,5)}–{String(a.end_time).slice(0,5)}</p></div><span className="h-fit rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">{a.status}</span></div></div>):<div className="rounded-2xl bg-slate-50 p-6 text-center text-sm text-slate-500">No appointments yet.</div>}</div></div></div></div>
}
