
import {useQuery} from '@tanstack/react-query';
import {api,apiError} from '../services/api';
import {useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Icon} from '../components/Icons';

export default function QueuePage(){
 const {id}=useParams(); const nav=useNavigate(); const [leaveError,setLeaveError]=useState('');
 const q=useQuery({queryKey:['position',id],queryFn:async()=>{const r=await api.get(`/queues/${id}/position`);return r.data},enabled:Boolean(id),refetchInterval:10000});
 useEffect(()=>{if(!id)return;const apiUrl=import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1';const wsBase=apiUrl.replace(/^http/,'ws').replace(/\/api\/v1\/?$/,'');const ws=new WebSocket(`${wsBase}/ws/queues/${id}`);ws.onmessage=()=>q.refetch();return()=>ws.close()},[id]);
 async function leave(){try{await api.post(`/queues/${id}/leave`);nav('/dashboard')}catch(e){setLeaveError(apiError(e,'Unable to leave queue.'))}}
 const d=q.data; const ahead=typeof d?.position==='number'?Math.max(0,d.position-1):0;
 if(q.isLoading)return <div className="page-wrap py-16"><div className="mx-auto max-w-2xl card p-10 text-center"><div className="mx-auto h-8 w-8 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600"/><p className="mt-4 font-semibold">Loading your place in line...</p></div></div>;
 if(q.isError)return <div className="page-wrap py-16"><div className="mx-auto max-w-xl card p-8 text-center"><p className="text-rose-600">Unable to load your queue.</p><button className="btn btn-primary mt-5" onClick={()=>q.refetch()}>Try again</button></div></div>;
 return <div className="page-wrap py-10 sm:py-16"><div className="mx-auto max-w-3xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-indigo-600">Live queue</p><h1 className="mt-2 text-4xl font-black">Your place is reserved.</h1><p className="mt-2 text-slate-500">This page updates automatically as the queue moves.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/> Live</span></div><div className="card mt-8 overflow-hidden"><div className="bg-slate-950 p-8 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">Your token</p><p className="mt-2 text-6xl font-black tracking-tight">{d?.token_code||'—'}</p><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><span className="h-2 w-2 rounded-full bg-emerald-400"/>{d?.status||'WAITING'}</div></div><div className="grid divide-y sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="p-7"><p className="text-sm font-semibold text-slate-500">People ahead</p><p className="mt-2 text-3xl font-black stat-number">{ahead}</p></div><div className="p-7"><p className="text-sm font-semibold text-slate-500">Estimated wait</p><p className="mt-2 text-3xl font-black stat-number">{d?.estimated_wait??0}<span className="ml-1 text-base font-bold text-slate-400">min</span></p></div><div className="p-7"><p className="text-sm font-semibold text-slate-500">Position</p><p className="mt-2 text-3xl font-black stat-number">#{d?.position??'—'}</p></div></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="card p-5"><p className="text-sm font-semibold text-slate-500">Actual waiting time</p><p className="mt-1 text-2xl font-black">{d?.wait_minutes??0} min</p><p className="mt-1 text-xs text-slate-400">Measured from queue join until service starts.</p></div><div className="card p-5"><p className="text-sm font-semibold text-slate-500">Service time</p><p className="mt-1 text-2xl font-black">{d?.service_minutes??0} min</p><p className="mt-1 text-xs text-slate-400">Measured from service start until completion.</p></div></div>{leaveError&&<p className="mt-4 text-sm font-semibold text-rose-600">{leaveError}</p>}<div className="mt-5 flex justify-end"><button className="btn btn-danger" onClick={leave}><Icon name="close" size={16}/> Leave queue</button></div><p className="mt-5 text-center text-xs text-slate-400">Keep this page open. QueueLess will refresh your status when the staff team advances the queue.</p></div></div>
}
