import {useState} from 'react';
import type {FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api,apiError} from '../services/api';

export default function ResetPassword(){
 const [params]=useSearchParams(); const token=params.get('token')||''; const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(password!==confirm){setError('Passwords do not match.');return}setLoading(true);try{const r=await api.post('/auth/reset-password',{token,password});setMessage(r.data.message)}catch(err){setError(apiError(err,'Unable to reset password.'))}finally{setLoading(false)}}
 return <div className="page-wrap py-14"><div className="mx-auto max-w-lg card p-8 sm:p-10"><p className="text-sm font-bold uppercase tracking-[.16em] text-indigo-600">Account recovery</p><h1 className="mt-2 text-3xl font-black">Set a new password</h1><p className="mt-3 text-slate-500">Choose a new password with at least 8 characters.</p>{!token?<div className="mt-7 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">This reset link is missing. Request a new one.</div>:<form onSubmit={submit} className="mt-7 space-y-5"><div><label className="label">New password</label><input className="input" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></div><div><label className="label">Confirm password</label><input className="input" type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></div>{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}<button disabled={loading||!password||!confirm} className="btn btn-primary w-full">{loading?'Updating...':'Reset password'}</button></form>}<Link to="/login" className="mt-6 block text-center text-sm font-bold text-indigo-600">Back to sign in</Link></div></div>
}
